version: '2'
networks:
  basic:
services:
<<<<<<< Updated upstream
<<<<<<< Updated upstream
  web:
    build:
      context: ./
<<<<<<< Updated upstream
      #dockerfile: ./docker_env(EN)/web/Dockerfile #全球用户使用
      dockerfile: ./docker_env(CN)/web/Dockerfile #国内用户使用
    container_name: greaterwms_web_v2.0.25
    restart: always
    volumes:
      - ./web_start.sh:/GreaterWMS/web_start.sh:rw
      - ./templates:/GreaterWMS/templates:rw
    ports:
      - '8080:8080'
    command: bash web_start.sh
=======
      dockerfile: ./docker_env(CN)/web/Dockerfile
    container_name: greaterwms_front_v2.0.25
=======
  greaterwms:
    build:
      context: ./
      dockerfile: ./docker_env(CN)/Dockerfile #国内用户
      #dockerfile:./docker_env(EN)Dockerfile #全球用户
    container_name: greaterwms_v2.0.25
>>>>>>> Stashed changes
    restart: always
    volumes:
      - ./templates/:/GreaterWMS/templates/:rw
      - ./web_start.sh:/GreaterWMS/web_start.sh:rw
<<<<<<< Updated upstream
    ports:
      - '8080:8080'
    command:
      - /bin/bash
      - -c
      - |
        bash web_start.sh
>>>>>>> Stashed changes
  backend:
    build:
      context: ./
      #dockerfile: ./docker_env(EN)/backend/Dockerfile #全球用户使用
      dockerfile: ./docker_env(CN)/backend/Dockerfile #国内用户使用
    container_name: greaterwms_backend_v2.0.25
    restart: always
    volumes:
      - ./:/GreaterWMS/:rw #将前目录挂载到容器下
<<<<<<< Updated upstream
    ports:
      - '8008:8008'      
    command:  bash backend_start.sh
    depends_on:
      - web
=======
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
=======
      - ./:/GreaterWMS/:rw #将前目录挂载到容器下
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
      - '8080:8080'
>>>>>>> Stashed changes
      - '8008:8008'
=======
  greaterwms:
    build:
      context: ./
      #dockerfile: ./docker_env(EN)/Dockerfile #全球用户使用
      dockerfile: ./docker_env(CN)/Dockerfile #国内用户使用
    container_name: greaterwms_v2.0.25
    restart: always
    volumes:
      - ./:/GreaterWMS/:rw #将前目录挂载到容器下
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
      - '8008:8008'
      - '8080:8080'
>>>>>>> Stashed changes
    command:
      - /bin/bash
      - -c
      - |
<<<<<<< Updated upstream
<<<<<<< Updated upstream
=======
        bash web_start.sh
>>>>>>> Stashed changes
        bash backend_start.sh
        /etc/init.d/supervisor start
=======
        bash web_start.sh
        bash backend_start.sh && /etc/init.d/supervisor start
>>>>>>> Stashed changes
  nginx:
    image: nginx:1.17.1
    container_name: greaterwms_v2.0.25_nginx
    restart: always
    privileged: true
    environment:
<<<<<<< Updated upstream
      - TZ=Asia/Shanghai
    ports:
      - 80:80
=======
     - TZ=Asia/Shanghai
    ports:
     - 80:80
>>>>>>> Stashed changes
      #- 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
<<<<<<< Updated upstream
      #- ./tempates:/GreaterWMS/templates:ro
      - ./static_new/:/GreaterWMS/static_new:ro
<<<<<<< Updated upstream
    links:
      - backend
>>>>>>> Stashed changes
    networks:
      - basic
=======

>>>>>>> Stashed changes
=======
      - ./static_new/:/GreaterWMS/static_new:ro
    networks:
      - basic
>>>>>>> Stashed changes
