version: '2'
networks:
  basic:
services:
  greaterwms:
    build:
      context: ./
      dockerfile: ./docker_env(CN)/Dockerfile #国内用户
      dockerfile:/docker_env(EN)Dockerfile #全球用户
    container_name: greaterwms_v2.0.25
    restart: always
    volumes:
      - ./templates/:/GreaterWMS/templates/:rw
      - ./web_start.sh:/GreaterWMS/web_start.sh:rw
      - ./:/GreaterWMS/:rw #将前目录挂载到容器下
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
      - '8080:8080'
      - '8008:8008'
    command:
      - /bin/bash
      - -c
      - |
        bash web_start.sh
        bash backend_start.sh
        /etc/init.d/supervisor start
  nginx:
    image: nginx:1.17.1
    container_name: greaterwms_v2.0.25_nginx
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
      #- 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./tempates:/GreaterWMS/templates:ro
      - ./static_new/:/GreaterWMS/static_new:ro

